### ISSUE TITLE
Great work guys! One thing to n

### ISSUE THREAD

**Issue by hgordon-git** [vusec/kasper#7]
Great work guys! One thing to note when you grab the repo the Stretch image is out of date so need to query archived branch to build the image or use  a different branch

**Comment by Jakob-Koschel** [comment]
Thanks!

Looks like stretch is now fully deprecated. I just fixed it in [faf9fb7db2f9d565e99b19bc3fdb3f8ada7dedee](https://github.com/vusec/kasper/commit/faf9fb7db2f9d565e99b19bc3fdb3f8ada7dedee).

I didn't test it but it *should* work.

If it doesn't, please open a new issue :)
